const char* index_html = ""
"<html>"
"<style>"
"#touchPad {"
"  border:2px;"
"  border-style:solid;"
"  border-color:black;"
"  width:100%;"
"  height:0;"
"  padding-bottom:100%;"
"}"
"</style>"
"<body>"
"  <meta name='viewport' content='width=device-width,user-scalable=no'>"
"  <div id='touchPad'>"
"  </div>"
"  <div>"
"    Power :"
"    <input type='range' name='points' min='0' max='10' value='0' onchange=\"callBB8('/power?value=' + this.value)\">"
"  </div>"
"</body>"
"<script>"
"var xmlHttp = new XMLHttpRequest();"
"function callBB8(theUrl) {"
"  xmlHttp.open('GET', theUrl, true);"
"  xmlHttp.send(null);"
"}"
""
"var touchPad = document.getElementById('touchPad');"
"touchPad.addEventListener('touchstart', touchStart, false);"
"touchPad.addEventListener('touchmove', touchStart, false);"
"touchPad.addEventListener('touchend', touchEnd, false);"
"touchPad.addEventListener('mousedown', touchStart, false);"
"touchPad.addEventListener('mousemove', mouseMove, false);"
"touchPad.addEventListener('mouseup', touchEnd, false);"
""
"function mouseMove(event) {"
"  if (event.which > 0) {"
"    touchStart(event);"
"  }"
"}"
""
"function touchStart(event) {"
"  callBB8('/rover?left=' + event.clientX + '&right=' + event.clientY);"
"}"
""
"function touchEnd(event) {"
"  callBB8('/rover?left=0&right=0');"
"}"
"</script>"
"</html>";
